# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sp_attack',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sp_defense',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(blank=True, default=False),
        ),
    ]
