# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20180513_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.IntegerField(blank=True, default=False, primary_key=True, serialize=False),
        ),
    ]
