# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20180519_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='number',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
